/*
     -----------------------------------------------------------

     Code generated by CRA.ModelLayer.ACC - API Code Generator
     http://components.biomamodelling.org/components/acc/help/ 

     Loic Manceau
     loic.manceau@inra.fr
     INRA
     7/23/2018 3:27:57 PM

     -----------------------------------------------------------
*/

using System;
using CRA.AgroManagement;
using CRA.ModelLayer.Strategy;


namespace SiriusQualityWheatLAI
{
    /// <summary>
    /// SiriusQualityWheatLAI component model interface   
    /// </summary>
    public interface IStrategySiriusQualityWheatLAI : IStrategy
    {
        /// <summary>
        /// Calculate method for models
        /// </summary>
        /// <param name=w>WheatLAIState Domain class contains the accessors to values</param>
        /// <param name=w1>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=w2>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=ae>AgroManagement objects of impact parameters</param>
        void Estimate
        ( WheatLAIState w, WheatLeafState w1, WheatLeafState w2, ActEvents ae);
        
        /// <summary>
        /// Test of pre conditions
        /// </summary>
        /// <param name=w>WheatLAIState Domain class contains the accessors to values</param>
        /// <param name=w1>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=w2>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=callID>Preconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPreConditions( WheatLAIState w, WheatLeafState w1, WheatLeafState w2, string callID);
        
        /// <summary>
        /// Test of post-conditions
        /// </summary>
        /// <param name=w>WheatLAIState Domain class contains the accessors to values</param>
        /// <param name=w1>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=w2>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=callID>Postconditions test context</param>
        /// <returns>List of violations</returns>
        string TestPostConditions( WheatLAIState w, WheatLeafState w1, WheatLeafState w2, string callID);
    
        /// <summary>
        /// Set parameters to the default value
        /// </summary>
        void SetParametersDefaultValue();
    }
}
