/*   
     ----------------------------------------------------------------
	 Code generated by CRA.ModelLayer.ACC - API Code Generator
     http://components.biomamodelling.org/components/acc/help/ 

     Loic Manceau
     loic.manceau@inra.fr
     INRA
     7/23/2018 3:27:57 PM
	 ----------------------------------------------------------------
*/

using System;
using System.Collections.Generic;
using System.Text;
using CRA.AgroManagement;
using CRA.ModelLayer.Core;

namespace SiriusQualityWheatLAI
{
    /// <summary>
    /// SiriusQualityWheatLAI component API 
    /// </summary>
    public class SiriusQualityWheatLAIAPI 
    {
        private string _resultPreConditions;
        private string _resultPostConditions;
        Preconditions p = new Preconditions();

        /// <summary>
        /// Calculate method for the component
        /// </summary>
        /// <param name=w>WheatLAIState Domain class contains the accessors to values</param>
        /// <param name=w1>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=w2>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=ae>AgroManagement objects of impact parameters</param>
        public void Estimate
		(IStrategySiriusQualityWheatLAI st, WheatLAIState w, WheatLeafState w1, WheatLeafState w2, ActEvents ae)
        {
            st.Estimate
			( w, w1, w2, ae);
        }
              
        /// <summary>
        /// Calculate method for the component with test of preconditions
        /// </summary>
        /// <param name=w>WheatLAIState Domain class contains the accessors to values</param>
        /// <param name=w1>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=w2>WheatLeafState Domain class contains the accessors to values</param>
        /// <param name=ae>AgroManagement objects of impact parameters</param>
        /// <param name="saveLog">Save log via a writer or show on screen</param>
        /// <param name="callID">Context description for violations</param>
        public void Estimate
            (IStrategySiriusQualityWheatLAI st, WheatLAIState w, WheatLeafState w1, WheatLeafState w2, ActEvents ae, bool saveLog, string callID)        
           {
            _resultPreConditions = String.Empty;
            _resultPostConditions = String.Empty;
            _resultPreConditions = st.TestPreConditions( w, w1, w2, callID);
            st.Estimate
			( w, w1, w2, ae);
            _resultPostConditions = st.TestPostConditions( w, w1, w2, callID);

            if (_resultPreConditions != String.Empty || _resultPostConditions != String.Empty)
            {
                p.TestsOut(_resultPreConditions + _resultPostConditions, saveLog, callID);
            }
        }

        /// <summary>
        /// Show the about form with access to the help and codedoc
        /// </summary>
        public void Info()
        {
            // The following assumes an about form called AboutBox
            //AboutBox a = new AboutBox();
            //a.ShowDialog();
        }
    }
}
 
